settings:
  language: english
  broadcast-to-console: true
  add-prefix-to-json: false
  special-list-for-newbies: ''
  connection:
    hostname: localhost:3306/minecraft
    username: user
    password: pass
    prefixes: rscm_
  fetch-interval-sec: 600
  use-metrics: true
internal:
  version: 5
