settings:
  language: english
  broadcast-to-console: true
  for-newbies:
    special-list-name: ''
    interval-sec:      604800
  add-prefix-to-json: false
  connection:
    hostname: localhost:3306/minecraft
    username: user
    password: pass
    prefixes: rscm_
  fetch-interval-sec: 600
  use-metrics: true
internal:
  version: 7
